### ISSUE TITLE
Incoming emails go to wrong swimlane

### ISSUE THREAD

**Issue by skorvek** [kanboard/plugin-mailgun#8]
The documentation for the plugin states that Emails go to the first active swimlane.

I have the default swimlane at the top- in settings it is labelled "INBOX (Default Swimlane), but incoming emails go to the next swimlane in the list below that.

**Comment by jtourt** [comment]
There is a bug in line 67 of EmailHandler.php.  It is set to call "$this->getSwimlaneId", but no such function exists.   Change to the following.

##### CORRECT:
EmailHandler.php:
Line 67:             
```php 
'swimlane_id'` => $this->swimlaneModel->getFirstActiveSwimlane($project),  
``` 

##### INCORRECT:
EmailHandler.php:
Line 67:             
```php
'swimlane_id'` => $this->getSwimlaneId($project), 
```

**Comment by fguillot** [comment]
@jtourt The method exists at line 147 https://github.com/kanboard/plugin-mailgun/blob/master/EmailHandler.php#L147

**Comment by jtourt** [comment]
Oh yeah.  So this a logic bug in getFirstActiveSwimlane.  The swimlanes table does not contain default swimlanes.  Default swimlanes are in the projects table.  The projects table would need to be queried for the status of show_default_swimlane. If show_default_swimlane is 1, then set swimlane_id to 0.  Otherwise, check the swimlanes table as the current getFirstActiveSwimlane function does.  Right?

**Comment by fguillot** [comment]
@jtourt yes

If you upgrade to Kanboard 1.0.31 that should solve your issue.
